# fly.toml app configuration file generated for small-frost-2068 on 2023-09-22T16:24:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "small-frost-2068"
primary_region = "waw"

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
