# fly.toml app configuration file generated for invoice-app-gg on 2023-06-13T19:35:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "invoice-app-gg"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
